import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/aur.toml"
]
[colors.primary]
foreground = "#7ca1f7"

[font]
size = 11.0

[font.normal]
family = "Hack Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 6
y = 0

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
